ncbi_sed_standalone/core/urls.py
from django.contrib import admin
from django.urls import path
from .views import core_interacting_organisations
from .views import core_document
from .views import core_folders
from .views.core_lk import lk_overview, lk_core, lk_logout, login_overview, authenticate_user
from .views.core_sed import search_staff, reviewdocuments_overview, incoming_overview, signdocuments_overview, recipients_overview
from .views.core_organisation import news_overview, employees_overview
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', login_required(lk_core), name='core'),
    path('space/', login_required(lk_overview), name='core-lk'),
    path('login/', login_overview, name='core-lk-login'),
    path('login/auth/', authenticate_user, name='core-lk-login-auth'),
    
    #СЭД
    path('staff-search/', login_required(search_staff), name='core-lk-staff-search'),
    path('organisation-search/', login_required(core_interacting_organisations.search_organisation), name='core-lk-organisation-search'),
    path('documents/', login_required(core_document.documents_overview), name='core-lk-documents'),
    path('documents-filter/', login_required(core_document.document_filters), name='core-lk-documents-filters'),
    path('documents/folders/', login_required(core_folders.folders_overview), name='core-lk-folders'),
    path('documents/folders/<int:folder_id>/', login_required(core_folders.folder_detail), name='folders-folder'),
    path('documents/add-review/', login_required(core_document.document_add_review), name='core-lk-document-review'),
    path('documents/delete-review/', login_required(core_document.document_delete_review), name='core-lk-document-delete-review'),
    path('documents/add-signer/', login_required(core_document.document_add_signer), name='document-add-signer'),
    path('documents/delete-signer/', login_required(core_document.document_delete_signer), name='document-delete-signer'),
    path('documents/add-addressee/', login_required(core_document.document_add_addressee), name='document-add-addressee'),
    path('documents/delete-addressee/', login_required(core_document.document_delete_addressee), name='document-delete-addressee'),
    path('documents/<str:doc_uid>/', login_required(core_document.document_detail), name='core-lk-document-detail'),
    path('documents/<str:doc_uuid>/registration/', login_required(core_document.document_registration), name='document-registration'),
    path('documents/<str:doc_uid>/upload-files/', login_required(core_document.document_upload_files), name='document-upload-files'),
    path('documents/<str:doc_uuid>/update-requisites/', login_required(core_document.document_update_requisites), name='document-update-requisites'),

    path('incoming/', login_required(incoming_overview), name='core-lk-incoming'),
    path('signing/', login_required(signdocuments_overview), name='core-lk-signing'),
    path('reviews/', login_required(reviewdocuments_overview), name='core-lk-reviews'),
    path('recipients/', login_required(recipients_overview), name='core-lk-recipients'),
    path('recipients/new/', login_required(core_interacting_organisations.interacting_organisation_new), name='core-lk-recipients-new'),

    path('create/document/', login_required(core_document.create_document), name='core-lk-create-document'),

    path('document-sign/', login_required(core_document.document_sign), name='core-lk-document-sign'),

    #ОРГАНИЗАЦИЯ
    path('organisation/news/', login_required(news_overview), name='core-lk-organisation-news'),
    path('organisation/employees/', login_required(employees_overview), name='core-lk-organisation-employees'),

    path('logout/', login_required(lk_logout), name='core-lk-logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ncbi_sed_standalone/ncbi_sed_standalone/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lk/', include('core.urls')),
    path('control/', include('appcontrol.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ncbi_sed_standalone/core/models.py
from django.db import models
from django.db.models import Max
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, Group, Permission
from datetime import datetime, timedelta
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.utils.text import slugify
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
import re
import uuid
import os


CATEGORY_DOCUMENT_CHOICES = [
    ('INCOMING_DOCUMENT', 'Входящий документ'),
    ('OUTGOING_DOCUMENT', 'Исходящий документ'),
    ('ORD', 'ОРД'),
    ('INTERNAL_DOCUMENT', 'Внутренний документ'),
    ('CONTRACTS', 'Договоры'),
    ('DPO_DOCUMENTS', 'Документы ДПО'),
]


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)

        if not email:
            raise ValueError('Учетная запись должна иметь адрес электронной почты')
        
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)

                
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Суперпользователь должен иметь is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    ROLE_SYSTEM = [
        ('STAFF', 'Сотрудник'),
        ('CHANCELLERY_CLERK', 'Делопроизводитель'),
        ('HEAD_CHANCELLERY', 'Руководитель канцелярии'),
        ('HEAD_DEPARTMENT', 'Руководитель подразделения'),
        ('RECTOR', 'Ректор')
    ]
    id = models.AutoField(primary_key=True)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(max_length=100, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_locked = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    first_name = models.CharField(_("Имя"), max_length=100)
    last_name = models.CharField(_("Фамилия"), max_length=100)
    patronymic = models.CharField(_("Отчество"), max_length=100, blank=True, null=True)
    role = models.CharField(_("Роль в системе"), choices=ROLE_SYSTEM, default='STAFF', max_length=50)
    username = None

    groups = models.ManyToManyField(
        Group,
        verbose_name=_("Группы"),
        blank=True,
        related_name="user_groups",
    )
    
    permissions = models.ManyToManyField(
        Permission, 
        verbose_name=_("Права пользователя"),
        blank=True,
        related_name="user_permissions",
    )


    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'patronymic']

    def get_full_name(self):
        """Возвращает полное имя (ФИО)"""
        parts = [self.last_name, self.first_name, self.patronymic]
        return " ".join(filter(None, parts))

    class Meta:
        verbose_name = _("Пользователь")
        verbose_name_plural = _("Пользователи")

class Organisation(models.Model):
    full_name = models.CharField(_("Полное наименование организации"), max_length=255)
    short_name = models.CharField(_("Сокращенное наименование организации"), max_length=45)
    inn = models.CharField(_("ИНН"), max_length=10)
    ogrn = models.CharField(_("ОГРН"), max_length=13)

    def __str__(self):
        return self.full_name
    
    def save(self, *args, **kwargs):
        if not self.pk and Organisation.objects.exists():
            raise ValueError("Нельзя создать более одной организации")
        super().save(*args, **kwargs)

class Post(models.Model):
    name = models.CharField(_("Должность"), max_length=120)

    def __str__(self):
        return self.name
    
class Department(models.Model):
    name = models.CharField(_("Отдел"), max_length=120)

    class Meta:
        verbose_name = _("Отдел")
        verbose_name_plural = _("Отделение")

    def __str__(self):
        return self.name

class Staff(models.Model):
    user = models.OneToOneField(User, verbose_name=_("Учетная запись"), on_delete=models.CASCADE, related_name='staff')
    organisation = models.ForeignKey("Organisation", verbose_name=_("Организация"), on_delete=models.CASCADE, blank=True)
    department = models.ForeignKey("Department", verbose_name=_("Отдел"), on_delete=models.CASCADE, blank=True)
    post = models.ForeignKey("Post", verbose_name=_("Должность"), on_delete=models.CASCADE, blank=True)

    def save(self, *args, **kwargs):
        if not self.organisation_id:
            self.organisation = Organisation.objects.first()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user} ({self.department})"

    class Meta:
        verbose_name = _("Сотрудник")
        verbose_name_plural = _("Сотрудники")

class InteractingOrganisations(models.Model):
    full_name = models.CharField(_("Полное наименование организации"), max_length=255)
    short_name = models.CharField(_("Сокращенное наименование организации"), max_length=155)
    inn = models.CharField(_("ИНН"), max_length=10)
    ogrn = models.CharField(_("ОГРН"), max_length=13)
    city = models.CharField(_("Город"), max_length=50, null=True)
    region = models.CharField(_("Регион"), max_length=50, null=True)
    index = models.CharField(_("Индекс"), max_length=50, null=True)
    legal_address = models.CharField(_("Юридический адрес"), max_length=120, null=True)
    
    class Meta:
        verbose_name = _("Взаимодействующая организация")
        verbose_name_plural = _("Взаимодействующие организации")

class DirectorsOrganisations(models.Model):
    first_name = models.CharField(_("Имя"), max_length=100)
    last_name = models.CharField(_("Фамилия"), max_length=100)
    patronymic = models.CharField(_("Отчество"), max_length=100, blank=True, null=True)
    post = models.CharField(_("Должность"), max_length=120, blank=True, null=False)
    organisation = models.OneToOneField(InteractingOrganisations, verbose_name=_("Организация"), on_delete=models.CASCADE)

    def get_full_name(self):
        """Возвращает полное имя (ФИО)"""
        parts = [self.last_name, self.first_name, self.patronymic]
        return " ".join(filter(None, parts))

    class Meta:
        verbose_name = _("Руководитель организации")
        verbose_name_plural = _("Руководители организаций")

class DocumentType(models.Model):
    category = models.CharField(max_length=55, choices=CATEGORY_DOCUMENT_CHOICES)
    name = models.CharField(_("Наименование"), unique=True, max_length=80)
    short_name = models.CharField(_("Сокращенное наименование"), max_length=20)
    description = models.CharField(_("Описание типа документа"), max_length=195)

    def __str__(self):
        return self.name

class Cases(models.Model):
    code = models.IntegerField(_("Код"))
    nomenclature = models.CharField(_("Номенклатура"), max_length=220)

    class Meta:
        verbose_name = _("Дело")
        verbose_name_plural = _("Дела")

"""
Модели относящийся к Документам
"""


class Document(models.Model):
    STATUS_DOCUMENT_CHOICES = [
        ('IN_WORKING', 'В работе'),
        ('SIGNED', 'Подписан'),
        ('SIGNING', 'Подписание'),
        ('WRITTEN_OFF', 'Списано'),
        ('NOT_ASSIGNED', 'Не назначен'),
    ]
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    category = models.CharField(max_length=55, choices=CATEGORY_DOCUMENT_CHOICES)
    brief = models.CharField(_("Краткое описание"), max_length=250, null=True)
    draft = models.BooleanField(_("Черновик"), default=True)
    case = models.ForeignKey(Cases, verbose_name=_("Дело"), on_delete=models.CASCADE, null=True)
    document_sheets = models.IntegerField(_("Листов документа"), null=True)
    application_sheets = models.IntegerField(_("Листов приложения"), null=True)
    author_work_card = models.ForeignKey(Staff, verbose_name=_("Автор рабочей карточки"), on_delete=models.CASCADE)
    note = models.CharField(_("Примечание"), max_length=250, null=True)
    status = models.CharField(_("Статус"), max_length=55, choices=STATUS_DOCUMENT_CHOICES, default='NOT_ASSIGNED')
    registration_number = models.CharField(_("Регистрационный номер"), max_length=110)
    created_at = models.DateTimeField(_("Дата создания в системе"), auto_now_add=True)

    class Meta:
        abstract = True


class IncomingDocuments(Document):
    type = models.ForeignKey(DocumentType, verbose_name=_("Тип документа"), on_delete=models.CASCADE)
    shared_access = models.BooleanField(_("Общий доступ"), default=True)
    signatory = models.ForeignKey(DirectorsOrganisations, verbose_name=_("Подписант"), on_delete=models.CASCADE, related_name='incoming_document_signatory', null=True)
    outgoing_number = models.CharField(_("Исходящий номер"), max_length=50, null=True)
    addressee = models.ForeignKey("Staff", verbose_name=_("Адресат"), on_delete=models.CASCADE, related_name='incoming_addressee', null=True)
    date = models.DateField(_("Дата регистрации"), auto_now_add=False, null=True)

    def save(self, *args, **kwargs):
        if not self.category:
            self.category = 'INCOMING_DOCUMENT'
        if not self.registration_number:
            all_numbers = IncomingDocuments.objects.filter(type=self.type).values_list('registration_number', flat=True)
            
            max_number = 0
            for reg_number in all_numbers:

ncbi_sed_standalone/core/views/core_folders.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.db.models import Count
from core.models import Folder, FolderObject, Staff, DocumentVisas, DirectorsOrganisations, InteractingOrganisations, IncomingDocuments, OutgoingDocuments, InternalDocuments, CATEGORY_DOCUMENT_CHOICES
from django.http import HttpResponse, HttpRequest, JsonResponse, Http404
from django_htmx.middleware import HtmxDetails
from .core_document import get_document_by_uuid, get_staff

class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails

def folders_overview(request):
    folders = Folder.objects.annotate(documents_count=Count('folderobject'))

    documents_url = reverse('core:core-lk-documents')

    crumbs = [
        {"name": "Работа с документами", "url": documents_url},
        {"name": "Папки", "url": f"{request.path}"}
    ]

    context = {
        'folders': folders,
        'crumbs': crumbs
    }

    if request.htmx:
        return render(request, './core/pages/sed/partials/partial_sed_folders.html', context)
    return render(request, './core/pages/sed/sed_folders.html', context)



def folder_detail(request: HtmxHttpRequest, *args, **kwargs) -> HttpResponse:
    folder_id = kwargs.get('folder_id')

    folder = Folder.objects.get(id=folder_id)
    files = FolderObject.objects.filter(folder=folder).values_list('document', flat=True)
    documents = []
    for file in files:
        doc = get_document_by_uuid(file)
        documents.append(doc)

    documents_url = reverse('core:core-lk-documents')
    
    crumbs = [
        {"name": "Работа с документами", "url": documents_url},
        {"name": "Папки", "url": reverse('core:core-lk-folders')},
        {"name": f"{folder.name}", "url": f"{request.path}"},
    ]

    context = {'folder': folder,
               'files': files, 
               'documents': documents,
               'crumbs': crumbs}


    if request.htmx:
        return render(request, './core/pages/sed/partials/folders/partial_sed_folder_detail.html', context)
    return render(request, './core/pages/sed/sed_folder_detail.html', context)

ncbi_sed_standalone/core/views/core_organisation.py
from django.shortcuts import render
from core.models import Staff

def news_overview(request):
    if request.htmx:
        return render(request, './core/pages/organisation/partials/partial_organisation_news.html')
    
    return render(request, './core/pages/organisation/organisation_news.html')

def employees_overview(request):

    context = {
                'users': Staff.objects.all()
            }


    if request.htmx:
        return render(request, './core/pages/organisation/partials/partial_organisation_employees.html', context)
    
    return render(request, './core/pages/organisation/organisation_employees.html', context)
    

ncbi_sed_standalone/core/views/core_reviews.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from typing import Optional, Type
from core.models import DocumentType, Document, Staff, DocumentVisas, InteractingOrganisations, IncomingDocuments, OutgoingDocuments, InternalDocuments, CATEGORY_DOCUMENT_CHOICES
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
import mimetypes
from django.db.models import Q
from django_htmx.middleware import HtmxDetails


class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails

ncbi_sed_standalone/core/templates/core/pages/sed/partials/documents/partial_document_select_staff.html
<div class="detail_object body__draft_select__form_control">
        <div class="form_container relative">
            <label for="search-staff">Выберете сотрудника</label>
            <input type="text" name="staff" 
                class="container_input inputing bscolor"
                hx-trigger="search, keyup delay:200ms changed"
                hx-get="{% url 'core:core-lk-staff-search' %}"  
                hx-target="#visas-container-results" 
                placeholder="Введите ФИО, должность или подразделение..."
                hx-swap="innerHTML transition:true"
                name="staff"
                id="search-staff"
                _="
                    on keyup 
                    if me.value.trim() then 
                        show #visas-container-results 
                        remove .fade-out from #visas-container-results
                        add .visible to #visas-container-results 
                    else 
                        remove .visible from #visas-container-results
                        add .fade-out to #visas-container-results 
                        wait 200ms 
                        then hide #visas-container-results
                        set #visas-container-results's innerHTML to ''
                "/>
                <ul class="form_container__result hidden fade-out overflow-y" id="visas-container-results"
                _="on htmx:afterSwap remove .hidden then add .visible"></ul>
        </div>
    <ul id="document-visas-list" class="detail_object body__draft_select__form_control reviews">
        {% include './partial_document_reviews_list.html' %}
    </ul>

</div>

ncbi_sed_standalone/core/templates/core/pages/sed/partials/documents/partial_sed_document_detail.html
{% load static %}
<script src="{% static '/js/document.js' %}" defer></script>
<script src="{% static '/js/document_crypto.js' %}" defer></script>
<div id="header-detail-document" class="app_container__content__section__header fixed background-white padding-bottom-1">
    {% include '../../../../components/breadcrumb.html' %}
    <div id="response-error" class="response_container error app_container__content__section__column min-height-fit"></div>
    <div class="app_container__content__section__header__row">
        <div class="app_container__content__section__column">
            {% if document.draft %}
    <div class="app_container__content__section__header__row draft_status">
        <svg width="15" height="15" viewBox="0 0 19 19" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path opacity="0.4" d="M16.625 17.417H2.375C2.05042 17.417 1.78125 17.1478 1.78125 16.8232C1.78125 16.4987 2.05042 16.2295 2.375 16.2295H16.625C16.9496 16.2295 17.2188 16.4987 17.2188 16.8232C17.2188 17.1478 16.9496 17.417 16.625 17.417Z" fill="#5B5B63"/>
            <path opacity="0.4" d="M15.0572 2.75466C13.5214 1.21882 12.0172 1.17924 10.4418 2.75466L9.48388 3.71257C9.40471 3.79174 9.37305 3.91841 9.40471 4.02924C10.0064 6.12716 11.6847 7.80549 13.7826 8.40715C13.8143 8.41506 13.846 8.42298 13.8776 8.42298C13.9647 8.42298 14.0439 8.39132 14.1072 8.32798L15.0572 7.37007C15.841 6.59424 16.221 5.84216 16.221 5.08216C16.2289 4.29841 15.8489 3.53841 15.0572 2.75466Z" fill="#5B5B63"/>
            <path d="M12.3586 9.12833C12.129 9.0175 11.9073 8.90667 11.6936 8.78C11.5194 8.67708 11.3531 8.56625 11.1869 8.4475C11.0523 8.36042 10.894 8.23375 10.7436 8.10708C10.7277 8.09917 10.6723 8.05167 10.609 7.98833C10.3477 7.76671 10.0548 7.48171 9.79356 7.16504C9.76981 7.14921 9.73023 7.09379 9.67481 7.02254C9.59564 6.92754 9.46106 6.76921 9.34231 6.58712C9.24731 6.46837 9.13648 6.29421 9.03356 6.12004C8.90689 5.90629 8.79606 5.69254 8.68523 5.47087C8.57439 5.23337 8.48731 5.00379 8.40814 4.79004L3.43649 9.76167C3.33358 9.86458 3.23858 10.0625 3.21483 10.1971L2.78733 13.2292C2.70816 13.7675 2.85858 14.2742 3.19108 14.6146C3.47608 14.8917 3.87191 15.0421 4.29941 15.0421C4.39441 15.0421 4.48941 15.0342 4.58441 15.0183L7.62441 14.5908C7.76691 14.5671 7.96481 14.4721 8.05981 14.3692L13.0315 9.3975C12.8098 9.31833 12.5961 9.23125 12.3586 9.12833Z" fill="#5B5B63"/>
            </svg>
            
            <h2 class="app_container__content__section__header__subtitle">
                    Черновик
                <input type="hidden" name="document_uuid" value="{{ document.uuid }}" />
            </h2>
        </div>
        {% else %}
        <div class="app_container__content__section__header__row status {{ document.status|lower }}">
            <svg width="13" height="13" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="7" cy="7" r="6.5"/>
                <path d="M7 11.5C6.68479 11.5 6.50935 11.4673 6.42116 11.4346C6.4261 11.4081 6.43592 11.3685 6.4556 11.3129C6.50452 11.1746 6.59103 11.0003 6.7143 10.7779C6.77582 10.6669 6.84615 10.5448 6.9216 10.4139C7.13268 10.0477 7.38375 9.61203 7.59351 9.15465C7.8831 8.52318 8.125 7.79079 8.125 7C8.125 6.20921 7.8831 5.47682 7.59351 4.84535C7.38375 4.38797 7.13268 3.95233 6.9216 3.58607C6.84615 3.45516 6.77582 3.33311 6.7143 3.22211C6.59103 2.99967 6.50452 2.82539 6.4556 2.68713C6.43592 2.63152 6.4261 2.59191 6.42116 2.56535C6.50935 2.53274 6.68479 2.5 7 2.5C9.48528 2.5 11.5 4.51472 11.5 7C11.5 9.48528 9.48528 11.5 7 11.5ZM5.51288 10.9793C5.48655 11.0537 5.46151 11.136 5.4435 11.2235C3.72529 10.5901 2.5 8.93815 2.5 7C2.5 5.06185 3.72529 3.40988 5.4435 2.77646C5.46151 2.86398 5.48655 2.94631 5.51288 3.02071C5.59113 3.24187 5.71219 3.47685 5.83963 3.70683C5.91582 3.84431 5.99568 3.98288 6.07704 4.12404C6.28164 4.47903 6.49569 4.85041 6.68453 5.2622C6.9436 5.82711 7.125 6.41008 7.125 7C7.125 7.58992 6.9436 8.17289 6.68453 8.7378C6.49569 9.14959 6.28164 9.52097 6.07704 9.87596C5.99568 10.0171 5.91582 10.1557 5.83963 10.2932C5.71219 10.5231 5.59113 10.7581 5.51288 10.9793Z"/>
                </svg>
                <h2>{{ document.get_status_display }}</h2>              
        </div>
        {% endif %}
    <div class="app_container__content__section__header__row headerline">
        <h1 class="app_container__content__section__header__title">{{ document.type }}</h1>
        <span class="app_container__content__section__header__element__headerline">
        </span>
    </div>
    <div class="app_container__content__section__header__row elements">
        <span class="app_container__content__section__header__element">№ {{ document.registration_number }}</span>
        <span class="app_container__content__section__header__element">{{ document.created_at }}</span>
    </div>
</div>
    <div class="app_container__content__section__header__buttons_panel">
        {% if document.draft %}
            <button class="button border gray">Удалить</button>
            <button hx-target="#app-content-section"
            hx-post="{% url 'core:document-registration' doc_uuid=document.uuid %}"
            hx-push-url="false"
            hx-swap="innerHTML transition: true"
            class="button border create">Зарегистрировать</button>
        {% else %}
            {% if document.author_work_card == request.user.staff %}
                <button class="button border gray">Редактировать</button>
            {% endif %}
            <button class="button border gray">Списать</button>
        {% endif %}
    </div>
</div>
</div>

<div class="app_container__content__row detail_container">
    <div class="app_container__content__section__body margin-0 flex">
        <div id="work-card-space" class="detail_object body border-left">
                {% include './detail/reviews/partial_work_card_review.html' %}
            <div class="detail_object body border-top border-bottom border-right">
                <div class="detail_object body__information">
                    <div class="detail_object body__information__header">
                    <h4 class="detail_object body__information__header__title">
                        Рабочая карточка документа
                    </h4>
                    <p>Укажите информацию о документе и зарегистрируйте его в системе</p>
                </div>
                    <ul class="detail_object body__information__description">
                        {% if document.draft %}
                            {% include './partial_sed_document_form_workcard.html' %}
                        {% else %}
                            {% include './partial_sed_document_form_workcard.html' %}
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="detail_object body border-bottom border-right">
                <div class="detail_object body__information">
                    <h4 class="detail_object body__information__title">
                        Реквизиты документа в организации-кореспонденте
                    </h4>
                    <ul class="detail_object body__information__description">
                        {% if document.draft %}
                            {% include './detail/requisites/partial_document_requisites.html' %}
                        {% else %}
                        <li class="detail_object body__information__description__element">
                            <span>Краткое описание:</span>
                            <span>{{ document.brief }}</span>
                        </li>
                        <li class="detail_object body__information__description__element">
                            <span>Листов документа:</span>
                            <span>{{ document.document_sheets }}</span>
                        </li>
                        <li class="detail_object body__information__description__element">
                            <span>Листов приложений:</span>
                            <span>{{ document.application_sheets }}</span>
                        </li>
                        <li class="detail_object body__information__description__element">
                            <span>Примечание:</span>
                            <span>{{ document.note }}</span>
                        </li>
                        <li class="detail_object body__information__description__element">
                            <span>Автор РК:</span>
                            <span>{{ document.author_work_card.user.get_full_name }}</span>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div id="document-upload-files" class="detail_object body border-bottom border-right">
                <div class="detail_object body__information">
                    <h4 class="detail_object body__information__title">
                        Файлы
                    </h4>
                    <form hx-encoding='multipart/form-data' hx-trigger="change" hx-swap="innerHTML transition: true" hx-target="#upload-files-list" hx-post="{% url 'core:document-upload-files' doc_uid=document.uuid %}">
                        {% if document.draft %}
                        <div class="upload_files__container">
                            <label
                            for="document-files"
                            class="upload_files__container__content"                            
                            _="
                            on drop halt the event
                            on dragover add .dragging to me
                            on dragleave remove .dragging from me
                            on drop remove .dragging from me
                            then 
                                set input to #document-files
                                set existingFiles to Array.from(input.files)
                                set newFiles to Array.from(event.dataTransfer.files)
                                set allFiles to existingFiles.concat(newFiles)
                                call updateInputFiles(input, allFiles)
                                trigger change on input">
                                <img src="{% static 'img/svg/app/_upload_files.svg' %}" alt="Загрузка файлов">
                                <h3 class="upload_files__container__title">Перетащите файлы в эту область или нажмите, чтобы выбрать</h3>
                                <input hidden multiple id="document-files" name="document_files" type="file">
                            </label>
                        </div>
                        {% endif %}
                        <ul id="upload-files-list" class="upload_files__container__content__files">
                            {% if document_files %}
                                {% include './detail/files/partial_document_files.html' %}
                            {% endif %}
                        </ul>
                </form>
                </div>
            </div>
        </div>
    </div>
    <div id="preview-files-container" 
    class="app_container__content__section__preview">
    {% if document_files %}
        {% include './detail/files/partial_document_preview.html' %}
    {% endif %}
    </div>
</div>