ncbi_sed_standalone/core/urls.py
from django.contrib import admin
from django.urls import path
from .views import core_interacting_organisations
from .views import core_document
from .views import core_folders
from .views.core_lk import lk_overview, lk_core, lk_logout, login_overview, authenticate_user
from .views.core_sed import search_staff, reviewdocuments_overview, incoming_overview, signdocuments_overview, recipients_overview
from .views.core_organisation import news_overview, employees_overview
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', login_required(lk_core), name='core'),
    path('space/', login_required(lk_overview), name='core-lk'),
    path('login/', login_overview, name='core-lk-login'),
    path('login/auth/', authenticate_user, name='core-lk-login-auth'),
    
    #СЭД
    path('staff-search/', login_required(search_staff), name='core-lk-staff-search'),
    path('organisation-search/', login_required(core_interacting_organisations.search_organisation), name='core-lk-organisation-search'),
    path('documents/', login_required(core_document.documents_overview), name='core-lk-documents'),
    path('documents-filter/', login_required(core_document.document_filters), name='core-lk-documents-filters'),
    path('documents/folders/', login_required(core_folders.folders_overview), name='core-lk-folders'),
    path('documents/folders/<int:folder_id>/', login_required(core_folders.folder_detail), name='folders-folder'),
    path('documents/add-review/', login_required(core_document.document_add_review), name='core-lk-document-review'),
    path('documents/delete-review/', login_required(core_document.document_delete_review), name='core-lk-document-delete-review'),
    path('documents/add-signer/', login_required(core_document.document_add_signer), name='document-add-signer'),
    path('documents/delete-signer/', login_required(core_document.document_delete_signer), name='document-delete-signer'),
    path('documents/add-addressee/', login_required(core_document.document_add_addressee), name='document-add-addressee'),
    path('documents/delete-addressee/', login_required(core_document.document_delete_addressee), name='document-delete-addressee'),
    path('documents/<str:doc_uid>/', login_required(core_document.document_detail), name='core-lk-document-detail'),
    path('documents/<str:doc_uuid>/registration/', login_required(core_document.document_registration), name='document-registration'),
    path('documents/<str:doc_uid>/upload-files/', login_required(core_document.document_upload_files), name='document-upload-files'),
    path('documents/<str:doc_uuid>/update-requisites/', login_required(core_document.document_update_requisites), name='document-update-requisites'),

    path('incoming/', login_required(incoming_overview), name='core-lk-incoming'),
    path('signing/', login_required(signdocuments_overview), name='core-lk-signing'),
    path('reviews/', login_required(reviewdocuments_overview), name='core-lk-reviews'),
    path('recipients/', login_required(recipients_overview), name='core-lk-recipients'),
    path('recipients/new/', login_required(core_interacting_organisations.interacting_organisation_new), name='core-lk-recipients-new'),

    path('create/document/', login_required(core_document.create_document), name='core-lk-create-document'),

    path('document-sign/', login_required(core_document.document_sign), name='core-lk-document-sign'),

    #ОРГАНИЗАЦИЯ
    path('organisation/news/', login_required(news_overview), name='core-lk-organisation-news'),
    path('organisation/employees/', login_required(employees_overview), name='core-lk-organisation-employees'),

    path('logout/', login_required(lk_logout), name='core-lk-logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ncbi_sed_standalone/ncbi_sed_standalone/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lk/', include('core.urls')),
    path('control/', include('appcontrol.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ncbi_sed_standalone/core/views/core_document.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from typing import Optional, Type
from django.contrib.contenttypes.models import ContentType
from core.models import DocumentType, Folder, DocumentFile, FolderObject, Staff, DocumentVisas, DirectorsOrganisations, InteractingOrganisations, IncomingDocuments, OutgoingDocuments, InternalDocuments, CATEGORY_DOCUMENT_CHOICES
from django.http import HttpResponse, HttpRequest, JsonResponse, Http404
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
from django.db import models
from django.utils.dateparse import parse_date
from django.apps import apps
import json
from django.views.decorators.csrf import csrf_exempt
import base64
# import pycades
from django.core.exceptions import ImproperlyConfigured
import mimetypes
from django.db.models import Count, Q
import os
from pdf2image import convert_from_path
from itertools import chain
from django_htmx.middleware import HtmxDetails
from django.template.context_processors import csrf
import logging
logging.basicConfig(level=logging.DEBUG)

class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails


def get_staff(user):
    return Staff.objects.get(user=user)

def get_document_by_uuid(document_uuid: str) -> Optional[Type]:
    """
    Получает документ по UUID из списка доступных моделей
    """
    for model in [IncomingDocuments, OutgoingDocuments, InternalDocuments]:
        try:
            return model.objects.get(uuid=document_uuid)
        except model.DoesNotExist:
            continue
    raise Http404("Документ с указанным UUID не найден")


def documents_overview(request):
    documents = chain(IncomingDocuments.objects.filter(draft=False), OutgoingDocuments.objects.filter(draft=False))
    folders = Folder.objects.annotate(documents_count=Count('folderobject'))

    document_types = CATEGORY_DOCUMENT_CHOICES
    staff = Staff.objects.all()

    address = chain(Staff.objects.all(), DirectorsOrganisations.objects.all())
    document_status = IncomingDocuments.STATUS_DOCUMENT_CHOICES

    context = {
        'documents': documents,
        'folders': folders,
        'staffs': staff,
        'address': address,
        'document_types': document_types,
        'document_status': document_status
    }

    if request.htmx:
        return render(request, './core/pages/sed/partials/partial_sed_documents.html', context)
    return render(request, './core/pages/sed/sed_documents.html', context)


def document_filters(request):
    document_signing = request.GET.get("document_signing")
    document_type = request.GET.get("document_type")
    document_address = request.GET.get("document_address")
    document_status = request.GET.get("document_status")
    document_short_note = request.GET.get("document_short_note")

    incoming_documents = IncomingDocuments.objects.filter(draft=False)
    outgoing_documents = OutgoingDocuments.objects.filter(draft=False)

    documents = chain(incoming_documents, outgoing_documents)

    if document_signing and document_signing != "all_documents":
        documents = filter(lambda doc: doc.signatory and doc.signatory.id == int(document_signing), documents)

    if document_type and document_type != "all_documents":
        documents = filter(lambda doc: doc.category == document_type, documents)

    if document_address and document_address != "all_documents":
        documents = filter(lambda doc: (hasattr(doc, 'addressee') and doc.addressee and doc.addressee.id == int(document_address)) or
                                    (hasattr(doc, 'outgoing_document_addressee') and doc.outgoing_document_addressee and doc.outgoing_document_addressee.id == int(document_address)),
                           documents)

    if document_status and document_status != "all_documents":
        documents = filter(lambda doc: doc.status == document_status, documents)

    if document_short_note:
        documents = filter(lambda doc: document_short_note.lower() in (doc.brief or '').lower(), documents)

    documents = list(documents)

    context = {'documents': documents}

    return render(request, "./core/pages/sed/partials/components/partial_documents.html", context)


@require_POST
def document_add_review(request: HtmxHttpRequest) -> HttpResponse:
    document_uuid = request.POST.get("document_uuid")
    staff_id = request.POST.get("staff_id")

    document = get_document_by_uuid(document_uuid)
    staff = get_object_or_404(Staff, id=staff_id)

    review, created = DocumentVisas.objects.get_or_create(
        document=document.uuid, 
        content_type=ContentType.objects.get_for_model(type(document)),
        staff=staff)

    reviews = DocumentVisas.objects.filter(document=document.uuid)

    context = {'document': document,
               'reviews': reviews}

    return render(request, "./core/pages/sed/partials/documents/detail/reviews/partial_document_reviews_list.html", context)

@require_POST
def document_delete_review(request: HtmxHttpRequest) -> HttpResponse:
    document_uuid = request.POST.get("document_uuid")
    staff_id = request.POST.get("staff_id")

    document = get_document_by_uuid(document_uuid)
    staff = get_object_or_404(Staff, id=staff_id)

    DocumentVisas.objects.get(document=document.uuid, staff=staff).delete()

    reviews = DocumentVisas.objects.filter(document=document.uuid)

    context = {'document': document,
                'reviews': reviews}

    return render(request, "./core/pages/sed/partials/documents/detail/reviews/partial_document_reviews_list.html", context)


def document_detail(request: HtmxHttpRequest, *args, **kwargs) -> HttpResponse:
    document_uuid = kwargs.get('doc_uid')
    preview_file_id = request.GET.get('preview')
    document = None

    document = get_document_by_uuid(document_uuid)


    documents_url = reverse('core:core-lk-documents')
    
    crumbs = [
        {"name": "Документы", "url": documents_url},
        {"name": "Черновики", "url": documents_url},
        {"name": f"{document.type} №{document.registration_number}", "url": f"{request.path}"},
    ]
    
    document_files = DocumentFile.objects.filter(document=document.uuid)
    document_file = DocumentFile.objects.filter(document=document.uuid).first()
    if preview_file_id:
        document_file = get_object_or_404(DocumentFile, id=preview_file_id)
    document_previews = []
    total_pages = 0

    previews, pages = get_file_preview(document_file)
    document_previews.extend(previews)
    total_pages += pages

    print(document_previews)


    context = {'document': document, 
               'crumbs': crumbs, 
               'total_pages': total_pages, 
                'document_previews': document_previews,
                'document_files': document_files
            }
    
    if not document.category == 'INCOMING_DOCUMENT':
        reviews = DocumentVisas.objects.filter(document=document.uuid)
        context['reviews'] = reviews

    if request.htmx:
        if preview_file_id:
            context = {'document_previews': document_previews, 'total_pages': total_pages, }
            return render(request, './core/pages/sed/partials/documents/detail/files/partial_document_preview.html', context)
        if 'reviews' in request.GET:
            return render(request, './core/pages/sed/partials/documents/detail/reviews/partial_reviews.html', context)
        elif 'signer' in request.GET:
            return render(request, './core/pages/sed/partials/documents/detail/signer/partial_signers.html', context)
        elif 'addressee' in request.GET:
            return render(request, './core/pages/sed/partials/documents/detail/addressee/partial_addressees.html', context)
        else:
            return render(request, './core/pages/sed/partials/documents/partial_sed_document_detail.html', context)
    return render(request, './core/pages/sed/sed_document_detail.html', context)

@require_POST
def document_update_requisites(request: HtmxHttpRequest, *args, **kwargs) -> HttpResponse:
    document_uuid = kwargs.get('doc_uuid')
    field_name = request.POST.get("field")
    value = request.POST.get(field_name)

    document = get_document_by_uuid(document_uuid)
    try:
        if field_name and hasattr(document, field_name):
            field = document._meta.get_field(field_name)

            if isinstance(field, models.DateField):
                value = parse_date(value)
            elif isinstance(field, models.IntegerField):
                value = int(value)

            setattr(document, field_name, value)
            document.save()
            return JsonResponse({"success": True})

    except Exception as e:
        return JsonResponse({"success": False, "error": str(e)})


def create_document(request):
    template = './core/pages/sed/partials/partial_sed_create_document.html'

    documents_url = reverse('core:core-lk-documents')

    if request.htmx:
        if request.method == 'GET':
            document_types = CATEGORY_DOCUMENT_CHOICES
            type_key = [choice[0] for choice in document_types]
            selected_type = request.GET.get('type')
            if selected_type and selected_type in type_key:
                context = {'types': DocumentType.objects.filter(category=selected_type)}
                return render(request, './core/pages/sed/partials/documents/partial_document_types.html', context) 
            
            documents_url = reverse('core:core-lk-documents')
            crumbs = [
                {"name": "Документы", "url": documents_url},
                {"name": "Регистрация нового документа", "url": f"{request.path}"},
            ]

            context = {
                'crumbs': crumbs,
                'document_types': document_types
            }
            return render(request, template, context)
        
        if request.method == 'POST':
            type_id = request.POST.get('type')
            if type_id:

ncbi_sed_standalone/core/views/core_folders.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.db.models import Count
from core.models import Folder, FolderObject, Staff, DocumentVisas, DirectorsOrganisations, InteractingOrganisations, IncomingDocuments, OutgoingDocuments, InternalDocuments, CATEGORY_DOCUMENT_CHOICES
from django.http import HttpResponse, HttpRequest, JsonResponse, Http404
from django_htmx.middleware import HtmxDetails
from .core_document import get_document_by_uuid, get_staff

class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails

def folders_overview(request):
    folders = Folder.objects.annotate(documents_count=Count('folderobject'))

    documents_url = reverse('core:core-lk-documents')

    crumbs = [
        {"name": "Работа с документами", "url": documents_url},
        {"name": "Папки", "url": f"{request.path}"}
    ]

    context = {
        'folders': folders,
        'crumbs': crumbs
    }

    if request.htmx:
        return render(request, './core/pages/sed/partials/partial_sed_folders.html', context)
    return render(request, './core/pages/sed/sed_folders.html', context)



def folder_detail(request: HtmxHttpRequest, *args, **kwargs) -> HttpResponse:
    folder_id = kwargs.get('folder_id')

    folder = Folder.objects.get(id=folder_id)
    files = FolderObject.objects.filter(folder=folder).values_list('document', flat=True)
    documents = []
    for file in files:
        doc = get_document_by_uuid(file)
        documents.append(doc)

    documents_url = reverse('core:core-lk-documents')
    
    crumbs = [
        {"name": "Работа с документами", "url": documents_url},
        {"name": "Папки", "url": reverse('core:core-lk-folders')},
        {"name": f"{folder.name}", "url": f"{request.path}"},
    ]

    context = {'folder': folder,
               'files': files, 
               'documents': documents,
               'crumbs': crumbs}


    if request.htmx:
        return render(request, './core/pages/sed/partials/folders/partial_sed_folder_detail.html', context)
    return render(request, './core/pages/sed/sed_folder_detail.html', context)

ncbi_sed_standalone/core/views/core_organisation.py
from django.shortcuts import render
from core.models import Staff

def news_overview(request):
    if request.htmx:
        return render(request, './core/pages/organisation/partials/partial_organisation_news.html')
    
    return render(request, './core/pages/organisation/organisation_news.html')

def employees_overview(request):

    context = {
                'users': Staff.objects.all()
            }


    if request.htmx:
        return render(request, './core/pages/organisation/partials/partial_organisation_employees.html', context)
    
    return render(request, './core/pages/organisation/organisation_employees.html', context)
    

ncbi_sed_standalone/core/templates/core/pages/sed/partials/documents/detail/addressee/partial_addressee_list.html
<li class="detail_object body__draft_select__form_control__staff">
    {% if document.draft %}
    <svg width="21" height="21" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M12 22C17.5 22 22 17.5 22 12C22 6.5 17.5 2 12 2C6.5 2 2 6.5 2 12C2 17.5 6.5 22 12 22Z" stroke="#059051" stroke-linecap="round" stroke-linejoin="round"/>
        <path d="M7.75 11.9999L10.58 14.8299L16.25 9.16992" stroke="#059051" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
    {% else %}
    <svg width="21" height="21" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M7.09351 6.34116C7.03517 6.33533 6.96517 6.33533 6.90101 6.34116C5.51266 6.29449 4.41016 5.15699 4.41016 3.75699C4.41016 2.32783 5.56516 1.16699 7.00017 1.16699C8.42934 1.16699 9.59017 2.32783 9.59017 3.75699C9.58434 5.15699 8.48184 6.29449 7.09351 6.34116Z" stroke="#70A8FF" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"/>
        <path d="M4.17691 8.49301C2.76525 9.43801 2.76525 10.978 4.17691 11.9172C5.78108 12.9905 8.4119 12.9905 10.0161 11.9172C11.4277 10.9722 11.4277 9.43217 10.0161 8.49301C8.41773 7.42551 5.78691 7.42551 4.17691 8.49301Z" stroke="#70A8FF" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        
    {% endif %}    
    <div class="detail_object body__draft_select__form_control__staff__column">     
        <div class="detail_object body__draft_select__form_control__staff__row">
            <p class="detail_object body__draft_select__form_control__staff__title">{% if document.addressee.get_full_name %}{{ document.addressee.get_full_name }}{% else %}{{ document.addressee.user.get_full_name }}{% endif %}</p>
            <span class="detail_object body__draft_select__form_control__staff__description">{{ document.addressee.post }}</span>
        </div>

        <span class="detail_object body__draft_select__form_control__staff__description">{% if document.addressee.organisation.short_name %}{{ document.addressee.organisation.short_name }}{% else %}{{ document.addressee.department }}{% endif %}</span>
</div>
{% if document.draft %}
<button 
hx-target="#document-addressee" 
hx-swap="innerHTML transition:true"
hx-trigger="click delay:200ms"
hx-post="{% url 'core:document-delete-addressee' %}"
hx-vals='{"document_uuid": "{{ document.uuid }}"}'
class="button delete" type="button"
_="on click 
    add .focused to #document-addressee
    remove .selected from #document-addressee">Удалить</button>
{% endif %}
</li>

ncbi_sed_standalone/core/templates/core/pages/sed/partials/documents/detail/addressee/partial_addressee_result.html
{% for addressee in addressees %}
<li class="form_container__result__staff">
    <a href="#!"
    hx-post="{% url 'core:document-add-addressee' %}"
    hx-vals='{"addressee_id": "{{ addressee.id }}", "source": "{{ source }}"}'
    hx-swap="innerHTML transition:true"
    hx-target="#document-addressee-list"
    hx-include="[name=document_uuid]" 
    hx-push-url="false"
    _="on click 
    set #search-addressee's value to '' 
    then hide #addressee-container-results
    wait 100ms 
    then add .selected to #document-addressee">
        <div class="form_container__result__staff__row organisation">
            {% if source == 'external_addressee' %}
            <svg width="19" height="19" viewBox="0 0 19 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g clip-path="url(#clip0_1862_2002)">
                <path d="M5.30385 14.2497H3.28511C2.15302 14.2497 1.58301 13.6797 1.58301 12.5476V3.28511C1.58301 2.15302 2.15302 1.58301 3.28511 1.58301H6.68927C7.82135 1.58301 8.39134 2.15302 8.39134 3.28511V4.74967" stroke="#70A8FF" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M13.7518 6.66582V15.5008C13.7518 16.7754 13.1184 17.4167 11.8439 17.4167H7.2205C5.94592 17.4167 5.30469 16.7754 5.30469 15.5008V6.66582C5.30469 5.39123 5.94592 4.75 7.2205 4.75H11.8439C13.1184 4.75 13.7518 5.39123 13.7518 6.66582Z" stroke="#70A8FF" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M10.6084 4.74967V3.28511C10.6084 2.15302 11.1784 1.58301 12.3105 1.58301H15.7146C16.8467 1.58301 17.4167 2.15302 17.4167 3.28511V12.5476C17.4167 13.6797 16.8467 14.2497 15.7146 14.2497H13.7513" stroke="#70A8FF" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M7.91699 8.70801H11.0837" stroke="#70A8FF" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M7.91699 11.083H11.0837" stroke="#70A8FF" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M9.5 17.417V15.042" stroke="#70A8FF" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                </g>
                <defs>
                <clipPath id="clip0_1862_2002">
                <rect width="19" height="19" fill="white"/>
                </clipPath>
                </defs>
                </svg>
            {% else %}
            <svg width="21" height="21" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M7.09351 6.34116C7.03517 6.33533 6.96517 6.33533 6.90101 6.34116C5.51266 6.29449 4.41016 5.15699 4.41016 3.75699C4.41016 2.32783 5.56516 1.16699 7.00017 1.16699C8.42934 1.16699 9.59017 2.32783 9.59017 3.75699C9.58434 5.15699 8.48184 6.29449 7.09351 6.34116Z" stroke="#70A8FF" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M4.17691 8.49301C2.76525 9.43801 2.76525 10.978 4.17691 11.9172C5.78108 12.9905 8.4119 12.9905 10.0161 11.9172C11.4277 10.9722 11.4277 9.43217 10.0161 8.49301C8.41773 7.42551 5.78691 7.42551 4.17691 8.49301Z" stroke="#70A8FF" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
            {% endif %}

            <div class="form_container__result__staff organisation">
                <h4>{% if source == 'external_addressee' %}{{ addressee.get_full_name }}{% else %}{{ addressee.user.get_full_name }}{% endif %}<span>{{ addressee.post }}</span></h4>
                <p>{% if source == 'external_addressee' %}{{ addressee.organisation.short_name }}{% else %}{{ addressee.department }}{% endif %}</p>
            </div>
            </div>
        </div>   
    </a> 
</li>
{% empty %}
    <li>Нет результатов</li>
{% endfor %}

ncbi_sed_standalone/core/templates/core/pages/sed/partials/documents/detail/addressee/partial_addressees.html
<div class="detail_object body__draft_select__form_control">
    {% if not document.addressee %}
    <div id="addressee-form-search" class="form_container relative">
        <label for="search-addressee">Выберете адресата</label>
        <input type="text" name="q" 
            class="container_input inputing bscolor"
            hx-trigger="search, keyup delay:200ms changed"
            {% if  document.category == 'INCOMING_DOCUMENT' %}
                hx-get="{% url 'core:core-lk-staff-search' %}"
                hx-vals='{"type": "addressee", "source": "internal_addressee"}'
                placeholder="Введите ФИО или должность..."
            {% else %}
                hx-get="{% url 'core:core-lk-organisation-search' %}"
                hx-vals='{"type": "addressee", "source": "external_addressee"}'
                placeholder="Введите данные организации или его руководителя..."
            {% endif %}
            hx-target="#addressee-container-results" 
            hx-swap="innerHTML transition:true"
            id="search-addressee"
            _="
                on keyup 
                if me.value.trim() then 
                    show #addressee-container-results
                    remove .fade-out from #addressee-container-results
                    add .visible to #addressee-container-results 
                else 
                    remove .visible from #addressee-container-results
                    add .fade-out to  #addressee-container-results 
                    wait 200ms 
                    then hide #addressee-container-results
                    set #addressee-container-results's innerHTML to ''
            "/>
            <ul class="form_container__result hidden fade-out overflow-y" id="addressee-container-results"
            _="on htmx:afterSwap remove .hidden then add .visible"></ul>
    </div>
    {% endif %}
<ul id="document-addressee-list" class="detail_object body__draft_select__form_control reviews"
_="on htmx:afterSwap add .hidden to #addressee-form-search">
    {% if document.addressee %}
        {% include './partial_addressee_list.html' %}
    {% endif %}
</ul>
</div>